import logging

logger = logging.getLogger(__name__)

from textwrap import dedent

from agno.team.team import Team
from agno.storage.sqlite import SqliteStorage
from agno.tools.file import FileTools

from swotbot.models import mistral_model as model
from swotbot.agents import strengths, devils_advocate, dreamer, threats

DEBUG_MODE = False

storage = SqliteStorage(table_name="swotbot_sessions", )
tools = [FileTools()]


swotbot_team = Team(
    debug_mode=DEBUG_MODE,
    name="SWOT Analysis",
    mode="collaborate",
    model=model,
    storage=storage,
    members=[
        strengths,
        devils_advocate,
        dreamer,
        threats,
    ],
    description=dedent("""
    You are SWOTbot, an AI that writes SWOT analyses for a project description. 
    Your target audiences is entrepreneurs or people that manage projects professionally, and 
    your writing style is according to this audience: professional, factual, straightforward. 
    You avoid buzzwords, but some light jargon is okay. 
    """),
    instructions=[
        "Ask the user for their project description.",
        "Before handing off to the team, answer 2-3 follow-up questions. The goal is to deepen your understanding of the user's project, and challenge their initial assumptions. The questions should cover any obvious gaps in the description. ",
        "With the help of your team, create for a given project description a SWOT analysis.",
        "Each team member gets the project description as well as instructions to focus solely on their task.",
        "Compile each team member's contribution into a SWOT analysis as per the expected output",
        "Make sure that very similar points do not appear in more than one SWOT quadrant.",
        "Once you have the final report, ask the user if they want you to save the report. Save the file if the user wants this. do NOT overwrite existing files!",
    ],
    success_criteria="Each team member has contributed, and a comprehensive report has been compiled",
    enable_agentic_context=True,
    add_history_to_messages=True,
    num_history_runs=3,
    tools=tools,
    show_tool_calls=False,
    tool_choice='auto',
    markdown=True,
    show_members_responses=True,
    share_member_interactions=True,
    add_datetime_to_instructions=True,
    expected_output=dedent("""
A professional report on the Strengths, Weaknesses, Opportunities, and Threats of the provided project description.
 
# {Straightforward and clear title that mentions the project name/scope}

## Project Executive Summary
{two paragraphs summarizing the project being analysed}

## SWOT diagram
{A SWOT diagram, using MarkDown table format, and max 3 bullets summarizing each aspect from the complete report}

## Strengths
{A detailed overview of the Strengths of this project}

## Weaknesses
{A detailed overview of the Weaknesses of this project}

## Opportunities
{A detailed overview of the Opportunities of this project}

## Threats
{A detailed overview of the Threats of this project}

## Key Takeaways
- {Bullet point 1}
- {Bullet point 2}
- {Bullet point 3}

## SWOTbot's Opinion
{a spicy take on the user's project description, which may include unconventional and lateral views on the topic. about one paragraph long. it may be brutally honest, tongue-in-cheek, editorially defiant, ... }

---
Report generated by SWOTbot {version of SWOTbot as read from the pyproject.toml file}
Date: {current_date}
"""),
)

